version: '3.8'

services:
  research-ppt:
    build: .
    volumes:
      - ./assets:/app/assets
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DISPLAY=host.docker.internal:0  # MacOS图形支持
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]